In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("Section 3:Classification/Logistic Regression/Social_Network_Ads.csv")
print(dataset.head())
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1:].values
print(X)
print(y)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0
[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25

# Splitting dataset to Training and test set

On changing random_state, we will get different result in confusion_matrix, accuracy_score

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

# Featuring scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Training K-NN model on training data

In [6]:
# KNN calculates euclidean distance between new data with trained data to classify new incoming data
from sklearn.neighbors import KNeighborsClassifier
# n_neighbors-No of neighbors to consider(default:5),weights 
classifier=KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)
classifier.fit(X_train,np.ravel(y_train))
y_pred=classifier.predict(X_test)
print(classifier.predict(sc.transform([[30,87000]])))
print(classifier.predict(sc.transform([[36,144000]])))

[0]
[1]


In [7]:
print(type(y_pred),type(y_test))
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]]


# Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
# Row - Actual Value, column - Predicted value
#   0       1(Predicted)
#0 50(c)    8
#1  4      38(C) # C - Correct Prediction
accuracy_score(y_test,y_pred)
tn, fp, fn, tp = cm.ravel()
print(tn, fp, fn, tp)
precision_0 = tn/(tn+fn)
print('precision_0 : ', precision_0)

[[50  8]
 [ 4 38]]
50 8 4 38
precision_0 :  0.9259259259259259


In [17]:
print(confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]))
tn, fp, fn, tp = confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]).ravel()
print(tn, fp, fn, tp)
tn, fp, fn, tp = confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]).reshape(-1)
print(tn, fp, fn, tp)

[[0 2]
 [1 1]]
0 2 1 1
0 2 1 1


In [14]:
from sklearn.metrics import classification_report
cp = classification_report(y_test,y_pred)
print(cp)

              precision    recall  f1-score   support

           0       0.93      0.86      0.89        58
           1       0.83      0.90      0.86        42

    accuracy                           0.88       100
   macro avg       0.88      0.88      0.88       100
weighted avg       0.88      0.88      0.88       100



# Cross Validation

# K Fold CV

ravel - returns array with same memory reference as original array shape (n_samples,). Changing value with refect changes in original array
flatten - returns copy of original array(shape (n_samples,1)). Changing value won't affect original array

In [34]:
from sklearn.model_selection import cross_val_score
# its creates 10 folds and apply prediction on all 10 folds. 
# If 1000 records are available in dataset, each fold contains 100 records(1000/10)
# 1st iteration-1st fold(0-100) is test set & rest is training set. 
# 2nd iteration-2nd fold(100-200) as testset & restis training set.
score=cross_val_score(classifier,X,y.ravel(),cv=10) 
print('Score : ', score)
print('Avg. Score : ', np.mean(score))
print(np.shape(y))
print(np.shape(y.ravel()))

Score :  [0.7   0.925 0.85  0.875 0.775 0.675 0.75  0.8   0.725 0.775]
Avg. Score :  0.7849999999999999
(400, 1)
(400,)


# K fold cross validation

In [46]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
accuracy=[]
kf=KFold(n_splits=10) # it won't shuffle the index
for train_index, test_index in kf.split(X,np.ravel(y)):
    print("Train Index : ", train_index, " Test Index : ", test_index)
    Xf_train,Xf_test=X[train_index], X[test_index]
    yf_train,yf_test=y[train_index], y[test_index]
    print("X1_train : ", len(Xf_train), " X1_test : ", len(Xf_test), " y1_train : ", len(yf_train)," y1_test : ", len(yf_test))
    classifier.fit(Xf_train,yf_train.ravel())
    prediction=classifier.predict(Xf_test)
    score=accuracy_score(prediction,yf_test)
    accuracy.append(score)

print("Accuracy : ", accuracy)
print("Avg. Accuracy : ", np.mean(accuracy))    

Train Index :  [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273
 274 275 276 277 278 279 280 281 282

# Stratified K fold cross validation

In [47]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
accuracy=[]
skf=StratifiedKFold(n_splits=10) # Shuffle train and test set
for train_index, test_index in skf.split(X,np.ravel(y)):
    print("Train Index : ", train_index, " Test Index : ", test_index)
    X1_train,X1_test=X[train_index], X[test_index]
    y1_train,y1_test=y[train_index], y[test_index]
    print("X1_train : ", len(X1_train), " X1_test : ", len(X1_test), " y1_train : ", len(y1_train)," y1_test : ", len(y1_test))
    classifier.fit(X1_train,y1_train.ravel())
    prediction=classifier.predict(X1_test)
    score=accuracy_score(prediction,y1_test)
    accuracy.append(score)

print("Accuracy : ", accuracy)
print("Avg. Accuracy : ", np.mean(accuracy))    

Train Index :  [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129
 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147
 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165
 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183
 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273
 274 275 276 277 278 279 280 281 282

In [50]:
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit
SEED = 43
SPLIT = 3
X_train = [0,1,2,3,4,5,6,7,8]
y_train = [0,0,0,0,0,0,1,1,1]   # note 6,7,8 are labelled class '1'

print("KFold, shuffle=False (default)")
kf = KFold(n_splits=SPLIT, random_state=SEED)
for train_index, test_index in kf.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)

print("KFold, shuffle=True")
kf = KFold(n_splits=SPLIT, shuffle=True, random_state=SEED)
for train_index, test_index in kf.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)

print("\nStratifiedKFold, shuffle=False (default)")
skf = StratifiedKFold(n_splits=SPLIT, random_state=SEED)
for train_index, test_index in skf.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)
    
print("StratifiedKFold, shuffle=True")
skf = StratifiedKFold(n_splits=SPLIT, shuffle=True, random_state=SEED)
for train_index, test_index in skf.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)
    
print("\nStratifiedShuffleSplit")
sss = StratifiedShuffleSplit(n_splits=SPLIT, random_state=SEED, test_size=3)
for train_index, test_index in sss.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)

print("\nStratifiedShuffleSplit (can customise test_size)")
sss = StratifiedShuffleSplit(n_splits=SPLIT, random_state=SEED, test_size=2)
for train_index, test_index in sss.split(X_train, y_train):
    print("TRAIN:", train_index, "TEST:", test_index)

KFold, shuffle=False (default)
TRAIN: [3 4 5 6 7 8] TEST: [0 1 2]
TRAIN: [0 1 2 6 7 8] TEST: [3 4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7 8]
KFold, shuffle=True
TRAIN: [0 1 2 4 5 7] TEST: [3 6 8]
TRAIN: [0 1 3 4 6 8] TEST: [2 5 7]
TRAIN: [2 3 5 6 7 8] TEST: [0 1 4]

StratifiedKFold, shuffle=False (default)
TRAIN: [2 3 4 5 7 8] TEST: [0 1 6]
TRAIN: [0 1 4 5 6 8] TEST: [2 3 7]
TRAIN: [0 1 2 3 6 7] TEST: [4 5 8]
StratifiedKFold, shuffle=True
TRAIN: [0 1 3 5 6 8] TEST: [2 4 7]
TRAIN: [0 2 4 5 7 8] TEST: [1 3 6]
TRAIN: [1 2 3 4 6 7] TEST: [0 5 8]

StratifiedShuffleSplit
TRAIN: [7 5 1 6 2 3] TEST: [0 4 8]
TRAIN: [6 5 1 8 4 2] TEST: [0 7 3]
TRAIN: [0 8 3 1 2 7] TEST: [5 6 4]

StratifiedShuffleSplit (can customise test_size)
TRAIN: [7 5 1 0 6 2 3] TEST: [8 4]
TRAIN: [3 5 1 6 8 4 2] TEST: [7 0]
TRAIN: [8 5 7 3 1 2 4] TEST: [6 0]


/home/vinoth/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(
