In [1]:
from sklearn import metrics

In [2]:
C="Cat"
D="Dog"
F="Fox"

In [7]:
#True Value
y_true = [C,C,C,C,C,C, F,F,F,F,F,F,F,F,F,F, D,D,D,D,D,D,D,D,D] # C-6,F-10,D-9
#Predicted Value
y_pred = [C,C,C,C,D,F, C,C,C,C,C,C,D,D,F,F, C,C,C,D,D,D,D,D,D]

#Print confusion matrix
print(metrics.confusion_matrix(y_true,y_pred))

#Print classification report
print(metrics.classification_report(y_true,y_pred, digits=3))

[[4 1 1]
 [3 6 0]
 [6 2 2]]
              precision    recall  f1-score   support

         Cat      0.308     0.667     0.421         6
         Dog      0.667     0.667     0.667         9
         Fox      0.667     0.200     0.308        10

    accuracy                          0.480        25
   macro avg      0.547     0.511     0.465        25
weighted avg      0.581     0.480     0.464        25



In [8]:
metrics.confusion_matrix(y_true,y_pred).reshape(-1)

array([4, 1, 1, 3, 6, 0, 6, 2, 2])